export default {
  BLOCK_FOR_TYPING: 'story/BLOCK_FOR_TYPING',
  CLICK_NEXT_BUTTON: 'story/CLICK_NEXT_BUTTON',
  FETCH_INITIAL: 'story/FETCH_INITIAL',
  LOAD_STORY: 'story/LOAD_STORY',
  LOAD_STORY_SUCCESS: 'story/LOAD_STORY_SUCCESS',
  STOP_TYPING: 'story/STOP_TYPING',
};
